apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-routing
spec:
 rules:
   - host: fleetmanmrc.com 
     http:
       paths:
         - path: /
           backend: 
             serviceName: miniweb
             servicePort: 80
