apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniweb
spec:
  selector:
    matchLabels:
      app: miniweb
  replicas: 1
  template:
    metadata:
      labels:
        app: miniweb

    spec:
      containers:
      - name: miniweb
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Never
        resources:
          requests:
             memory: 100Mi
             cpu: 50m


---


apiVersion: v1
kind: Service

metadata:
  name: miniweb

spec:
  selector:
    app: miniweb

  ports:
    - name: http
      port: 80
      nodePort: 30080
    



  type: NodePort
